version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "10.4.11.236:8000:8000"
    env_file:
      - .env
    container_name: trainylics-backend
    restart: always

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: http://10.4.11.236:8000
    ports:
      - "10.4.11.236:80:80"
    container_name: trainylics-frontend
    depends_on:
      - backend
    restart: always
